all: *.cpp ../include/*.h
	g++ -L/usr/local/lib/ -lGLEW -lglut -lSDL -lSDL_image -I../include -I/home/martin/code/cpp/ -I/usr/local/include/SDL -I/usr/include/SDL -g  *.cpp -o ../lab06
#-DSHADER_PREFIX=\"Shaders\"